apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: default
  labels:
    app: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: 250037329208.dkr.ecr.us-east-1.amazonaws.com/api-ecr-dev:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: RAG_SERVICE_URL
          value: "http://rag-service.default.svc.cluster.local:8081"
        - name: API_USERNAME
          value: "admin"
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: API_PASSWORD
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  selector:
    app: api-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 