apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - manifests/litellm-servicemonitor.yaml
  - manifests/bifrost-servicemonitor.yaml
  - manifests/langfuse-servicemonitor.yaml
  - manifests/vllm-servicemonitor.yaml
  - manifests/dcgm-servicemonitor.yaml
