apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
  name: azure-sync
  namespace: default
spec:
  parameters:
    clientID: <Managed Identity Client ID Here>
    keyvaultName: <literal key vault name>
    objects: |
      array:
        - |
          objectName: bitbucket
          objectType: secret                     # object types: secret, key or cert
          objectAlias: secretalias
    tenantId: <Tenant ID From Keyvault / Azure Here - Retrieved from Keyvault -> Json View>
    usePodIdentity: 'false'
    useVMManagedIdentity: 'false'
  provider: azure
  secretObjects:
    - data:
        - key: bitbucket_token
          objectName: secretalias
      secretName: bitbucket
      type: Opaque
