apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - manifests/postgres-statefulset.yaml
  - manifests/init-scripts.yaml
  - secrets/postgres-secret.yaml

helmCharts:
  - name: postgresql
    path: /tmp
    valuesFile: values.yaml
    
configMapGenerator:
  - name: postgres-init-scripts
    files:
      - manifests/init-scripts/create-langfuse-db.sql
      - manifests/init-scripts/create-bifrost-db.sql