apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: inference
  labels:
    app.kubernetes.io/name: vllm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 8001
      targetPort: 8001
  selector:
    app.kubernetes.io/name: vllm