apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/api-deployment.yaml
  - api/hpa.yaml
  - rag/rag-deployment.yaml
  - rag/hpa.yaml
  - postgres/postgres-config.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-statefulset.yaml
  - ingress.yaml

namespace: default 