apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: default
type: Opaque
data:
  # Ideally retrieved from AWS Secrets Manager and a secretProviderClass is referenced
  # echo -n "your-secret-value" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL2FwaV91c2VyOmFwaV9wYXNzd29yZEBwb3N0Z3JlczozMDMwL2FwaV9kYg== # replace with real encoded value
  API_PASSWORD: cGFzc3dvcmQ= # replace with real encoded value
