tools:
    shell:
        allow:
            - cd *
            - echo *
            - grep *
            - docker image *
            - env
            - sed *
            - aws *
            - aws sts *
            - head *
            - docker push *
            - ls *
            - cat *
            - find *
            - curl *
            - tr *
            - fold *
            - python3 *
            - launchctl list
            - launchctl print *
