tools:
    shell:
        allow:
            - cd *
            - echo *
            - grep *
            - docker image *
            - env
            - sed *
            - aws *
            - aws sts *
            - head *
            - docker push *
