apiVersion: v2
name: prefect-prometheus
description: A Helm chart for Kubernetes

type: application

version: 1.3.0
appVersion: 1.3.0
description: A Helm Chart to expose Batch State Metrics using Prometheus.
home: https://github.com/PrefectHQ/prefect-recipes
keywords:
- prometheus
- batch
maintainers:
- email: chris.b@prefect.io
  name: prefectcboyd
sources:
- https://prefect.io
