apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

dependsOn:
  - name: sources

resources:
  - cert-manager-helmrelease.yaml
  - ingress-nginx-helmrelease.yaml
  - gpu-operator-helmrelease.yaml