#k apply -f <file>
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cam-eks-deployment-aws-secrets
  namespace: cam
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
        - objectName: "prd_cps_dsci_etl_svc_cloud_conn_str"
          objectType: "secretsmanager"
          jmesPath:
             - path: "\"cam-eks-snowflake-secret\""
               objectAlias: snowflakepass
  secretObjects:
    - secretName: cam-eks-secret
      type: Opaque
      data:
        - key: snowflakepw
          objectName: snowflakepass
