version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-api_db}
      POSTGRES_USER: ${DB_USER:-api_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-api_password}
      DATABASE_URL: postgresql://${DB_USER:-api_user}:${DB_PASSWORD:-api_password}@postgres:5432/${DB_NAME:-api_db}
    restart: unless-stopped

volumes:
  postgres_data:
